---
- name: install python
  apt:
    name: python3-pip
  become: true 
- name: install awscli
  pip:
    name: awscli
    umask: '0022'
    executable: pip3
  become: "{{ vagrant_user }}"
- name: ssh aws creds
  lineinfile: 
    dest: '/etc/ssh/sshd_config'
    regexp: '^AcceptEnv LANG LC_/*'
    line: 'AcceptEnv LANG LC_* AWS_*'
  notify: restart sshd
